### ISSUE TITLE
create a fall declaration of fall on dependance app 

### ISSUE THREAD

**Issue by mehditerraneen** [opefitoo/inur.django#146]
document spec is [here](https://docs.google.com/document/d/1OfjDwtHKKfSR8_9gOn41ymvwZPww96mh/edit?usp=sharing&ouid=102019169137293207493&rtpof=true&sd=true)

**Comment by mehditerraneen** [comment]
https://www.loom.com/share/02681fab32a742d0b1269d99343cea83

**Comment by aamadou** [comment]
@mehditerraneen I pulled the branch but I can see that the report_pictures_description is still "required", I thought you fixed this on your side,
 do you want me to do the fix in this branch?

**Comment by aamadou** [comment]
Also the loom video is mute but I got the feeling you were talking through it!

**Comment by aamadou** [comment]
I pushed a draft solution in the commit 
https://github.com/opefitoo/inur.django/commit/a8cbc2dc3bd7b69fe44fe52861c4317ddec6ee28
is this the way you want to go?
