### ISSUE TITLE
If Birthday in December, it could be missed by the Birthday event processor

### ISSUE THREAD

**Issue by aamadou** [opefitoo/inur.django#51]
In the event processor we have this:

    thisday = timezone.datetime.today()
    lastday = thisday + timezone.timedelta(days=+num_days)

    myregexp = re.compile('^[0-9]{4}(' + str(thisday.month).zfill(2) + '|' + str(lastday.month).zfill(2) + ')')

    patients = Patient.objects.filter(code_sn__regex=myregexp.pattern).filter(date_of_death__isnull=True)
    for patient in patients:
        patient_birthday = extract_birth_date(patient.code_sn)
        if patient_birthday.replace(year=lastday.year) <= lastday:

if thisday is in December, the search period would span two years N and N+1, so I added these lines in my code:

         active_year = thisday.year    
         if (patient_birthday.month!=thisday.month):
               active_year = lastday.year

This won't work with the new refactored code, but we can do it this way maybe :

       patient_birthday = extract_birth_date(patient.code_sn)
       active_year = lastday.year 
        if patient_birthday.month>lastday.month:
            active_year -=1 
        if patient_birthday.replace(year=active_year) <= lastday:

**Comment by mehditerraneen** [comment]
@aamadou I simplified a bit a more and changed the regex to get directly the right `Patients` can you have a look ?
